apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: hermes
spec:
  selector:
    app: api-gateway
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: api-gateway
   namespace: hermes
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: api-gateway
     spec:
       containers:
         - name: api-gateway
           image: node:6-alpine
           command: ["/bin/sh"]
           args: ["-c", "cd api-gateway;npm install;node app.js;"]
           ports:
             - containerPort: 3000